from math import *

def vier(): 
    print("Nul is", int(4+4-4-4))
    print("Een is", int(44/44))
    print("Twee is", int(sqrt(4)))
    print("Drie is", int((4+4+4)/4))
    print("Vier is", int((4*4)/4))
    print("Vijf is", int(((4*4)+4)/4))
    print("Zes is", int((4*.4)+4.4))
    print("Zeven is",int(44/4-4))
    print("Acht is", int((4+4.4)-0.4))
    print("Negen is",int(4/4+4+4))
    print("Tien is", int(44/4.4))
    print("Elf is", int((4/.4)+(4/4)))
    print("Twaalf is",int(4+4+4))
    print("Dertien is",int(factorial(4)-(44/4)))
    print("Viertien is",int((4*(4-.4))-.4))
    print("Vijftien is",int((44/4)+4)) 
    print("Zestien is",int(.4*(44-4)))
    print("Zeventien is",int(4/4+4*4)) 
    print("Achttien is",int(44*.4+.4)) 
    print("Negentien is",int(factorial(4)-4-(4/4))) 
    print("Twintig is",int(4*(4/4+4))) 